services:
  - type: web
    name: odoo-web
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: DATABASE_URL
        value: postgresql://odoo_db_8iua_user:A8tTE7TYqRjrwtd5LVUA9lbqGyDQTUbi@dpg-d01hkladbo4c738p70mg-a/odoo_db_8iua
    ports:
      - 8069
